### PR TITLE
Fire "tap" event on mouse click even on touch devices

### LINKED ISSUE #20: Click events do not fire in Chrome Win 8.1 touch laptops
OS: Win 8.1 (touch enabled)
Browser: Chrome 42.0

The "tap" events do not fire when the mouse is used to perform an interaction. A mouse click does not fire a "tap" event. Touch interactions however do work correctly and fire a "tap" event.

This issue has been reproduced on several touch enabled Win 8.1 laptops. This seems to affect only Chrome. Both Firefox and IE work fine i.e. they do fire "tap" events on click.

On investigation, it appears that `isTouch` is `true` on Chrome and when this is the case, mouse events are not registered.

https://github.com/GianlucaGuarini/Tocca.js/blob/master/Tocca.js#L158

I'm wondering why the lib is listening only to touch events when a touch device is detected? Shouldn't it listen to both touch and click since it could be a touch and click device? 

My suggestion would be to not listen to click events only if the user has explicitly asked for that via `JUST_ON_TOUCH_DEVICES`. In all other cases, it should listen to both.

### PR DESCRIPTION
**Pull request by anushr**
Listen to click events even on touch enabled devices since newer laptops support both click and touch.

Fixes #20

### CODE REVIEW

**Comment by GianlucaGuarini** [comment]
I do not think this is the right patch for your problem..with this you force all the touch device triggering the callbacks only on the mouse events `mousedown mouseup`...

**Comment by anushr** [comment]
I've tested this fix on both, touch-only devices (Android and iPhone) as well as on hybrid devices (Win 8.1 touch). They both appear to function well. The hybrid devices respond to both touch and click events and the touch-only devices respond to touch events.

From my understanding, the only thing this PR does is to listen to mouse events _in addition to_ the already listened on touch events. It does not turn off the other.

Could you please have a look again; I'll defer to your recommendation. Let me know if I am misunderstanding something.

**Comment by GianlucaGuarini** [comment]
I need to reconsider your pull request and check again if it works on all the devices

**Comment by GianlucaGuarini** [comment]
this issue should be fixed in the new 0.2.0 beta release - @anushr could you test it please?

**Comment by anushr** [comment]
@GianlucaGuarini that's awesome! I'll test it out in the next couple days. Don't have a touch laptop right now, but will try to get my hands on one.

**Comment by GianlucaGuarini** [comment]
@anushr any feedback? I am waiting to roll out the stable release

**Pull request closed without merging**
